name: Build and Deploy .NET 8 Application

on:
  push:
    branches:
      - main

jobs:
  # Job 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore src/WebApi/WebApi.csproj

      - name: Build
        run: dotnet build src/WebApi/WebApi.csproj

  # Job 2: Deploy
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Build and Push Docker Compose images
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 891377307312.dkr.ecr.us-east-1.amazonaws.com
          docker build -t fiap-sa-api .
          docker tag fiap-sa-api 891377307312.dkr.ecr.$AWS_REGION.amazonaws.com/fiap-sa-api:latest
          docker push 891377307312.dkr.ecr.$AWS_REGION.amazonaws.com/fiap-sa-api:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/services/mssql-fiap-sa-pv.yaml
          kubectl apply -f k8s/services/mssql-fiap-sa-pvc.yaml
          kubectl apply -f k8s/services/mssql-secret-fiap-sa.yaml
          kubectl apply -f k8s/services/mssql-fiap-sa.yaml
          kubectl apply -f k8s/services/mssql-service-fiap-sa.yaml
          kubectl apply -f k8s/application/configmap-fiap-sa.yaml
          kubectl apply -f k8s/application/secret-fiap-sa.yaml
          kubectl apply -f k8s/application/deployment-fiap-sa.yaml
          kubectl apply -f k8s/application/service-fiap-sa.yaml
